Iss01 - global and dev procs updated

diff --git a/files/bash_global_procs b/files/bash_global_procs
--- a/files/bash_global_procs
+++ b/files/bash_global_procs
@@ -1,1 +1,48 @@
 #!/usr/bin/env bash
+
+function cheat() {
+    /usr/bin/curl https://cheat.sh/$1
+}
+
+function dir_list() {
+    local f
+
+    for f in "$1"/*; do
+        [[ -d $f ]] && echo "  D >>: $f" && dir_list "$f"
+        [[ -f $f ]] && echo "    >>: $f"
+    done
+}
+
+function messenger() {
+    if [ -z "${1}" ] || [ -z "${2}" ]; then
+        return
+    fi
+
+    local RED="\e[31m"
+    local GREEN="\e[32m"
+    local YELLOW="\e[33m"
+    local BLUE="\e[34m"
+    local MAGENTA="\e[35m"
+    local CYAN="\e[36m"
+    local RESET="\e[0m"
+    local MTYPE="${1}"
+    local MSG="${2}"
+
+    case ${MTYPE} in
+        info) echo -e " [${GREEN}#${RESET}] ${BLUE}${MSG}${RESET}";;
+        progress) echo -e " [${GREEN}+${RESET}] ${CYAN}${MSG}${RESET}";;
+        recommend) echo -e " [${MAGENTA}!${RESET}] ${MAGENTA}${MSG}${RESET}";;
+        warn) echo -e " [${YELLOW}*${RESET}] ${YELLOW}WARNING! ${MSG}${RESET}";;
+        error) echo -e " [${RED}!${RESET}] ${RED}ERROR! ${MSG}${RESET}";;
+        fatal) echo -e " [${RED}!${RESET}] ${RED}ERROR! ${MSG}${RESET}"
+                exit 1;;
+        *) echo -e " [?] UNKNOWN: ${MSG}";;
+    esac
+}
+
+function remove_outdated_snaps() {
+    snap list --all | mawk '/disabled/{print $1, $3}' |
+    while read snapname revision; do
+        sudo snap remove "$snapname" --revision="$revision"
+    done
+}
